
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: 程丽
tagline: Full Stack Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: krystalcl001@gmail.com
phone: 156 2370 4115
website: blog.webjeda.com #do not add http://
linkedin: alandoe
github: https://github.com/krystalcl
QQ: 164693817

#Update all the sections by editing the files inside _includes folder.
